### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by rodude123** [MCMic/workflow_kitinerary#32]
How do you set this up I see this when trying to set up a flow. I've installed `libpimitinerary-dev` on ubuntu 22.04. I still get this issue. In the dev console, I see a 400 bad request error.

My system:
- Ubuntu 22.04 `Linux cloud.rohitpai.co.uk 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- LAMP Stack
- Nextcloud 25.0.2

 
![image](https://user-images.githubusercontent.com/10896262/211194883-23842a9e-497c-4e6c-8c6e-7dacbccc6c8a.png)

**Comment by MCMic** [comment]
Hello,

This error is unexpected.

I can reproduce it on my instance, so nothing wrong with your configuration.
It is not specific to my application, I can reproduce that with any workflow.
Can you open a ticket at https://github.com/nextcloud/server since the workflowengine application is hosted there?

In the mean time, I advise to use a tag instead of a mime type for the trigger as that works, and if you tag a folder the workflow applies to any file in the folder.

**Comment by rodude123** [comment]
> Hello,
> 
> This error is unexpected.
> 
> I can reproduce it on my instance, so nothing wrong with your configuration. It is not specific to my application, I can reproduce that with any workflow. Can you open a ticket at https://github.com/nextcloud/server since the workflowengine application is hosted there?
> 
> In the mean time, I advise to use a tag instead of a mime type for the trigger as that works, and if you tag a folder the workflow applies to any file in the folder.

I've tried using a tag but that wouldn't work either

**Comment by rodude123** [comment]
When I try and tag I get this 
![image](https://user-images.githubusercontent.com/10896262/211847767-55e065f2-1f89-48fd-b25a-b8647fbda8fd.png)
which looks fine but if I reload the page I get this 
![image](https://user-images.githubusercontent.com/10896262/211847875-1df4c007-33ad-4df5-a805-fc6bf09ed8e7.png)
And it still doesn't work if a folder is tagged with it

**Comment by MCMic** [comment]
Yeah when reloading the page the configuration do not appear sadly, this is what #35 is about.

Can you set your log level to debug and upload a ticket to a folder tagged with the tag you selected? You should have some info in the log.
Most likely the application is failing to run kitinerary.
You either need to have it installed on your system, or have flatpak.
Otherwise there is a statically linked binary with the app but I think you have to do `chmod +x`, on my system it was not executable. And on my system it does not work anyway, it complains about glibc version.

If you can install kitinerary directly on your system that’s the best way because you control which version you run and you will be able to update it when there are new versions.

**Comment by MCMic** [comment]
> I've installed libpimitinerary-dev on ubuntu 22.04. I still get this issue. In the dev console, I see a 400 bad request error.

Oh, I missed that part.
Installing the package is often not enough for kitinerary-extractor to be in the PATH, you have to symlink it to /usr/local/bin for instance, given that is in your path.
Packages usually put the binary in `/usr/lib/x86_64-linux-gnu/libexec/kf5/kitinerary-extractor`, which is not in the path.

**Comment by TraceyC77** [comment]
I'm having the same problem. I have the same setup as the original poster.
Nextcloud Hub 3 (25.0.2) on Ubuntu 22.04.1

I have installed libkpimitinerary5 and libkpimitinerary-dev. System is up to date.
I created the symlink as you described above, and the library is now in the system path.

```
❯ ll /usr/local/bin/kitinerary-extractor
lrwxrwxrwx 1 root root 58 Jan 16 21:58 /usr/local/bin/kitinerary-extractor -> /usr/lib/x86_64-linux-gnu/libexec/kf5/kitinerary-extractor*
```

I have a couple of files in a folder with the tag 'kitinerary'. When I try to set up the Flow using that tag, I get the same error as described in the original post.  I am also seeing a 400 error for the save operation.

POST https://nextcloud.xxx.xxx/ocs/v2.php/apps/workflowengine/api/v1/workflows/user?format=json 400 (Bad request)

**Comment by MCMic** [comment]
@TraceyC77 So you are not able to set up the flow or it is not able to run?

In the original post the configuration was incorrect since mimetype and matches cannot be used together.
To set up with a tag, you have to use tag, is, and select your tag, as in the screencast in the readme.
Does that say active when you validate it?

**Comment by TraceyC77** [comment]
While going through the flow again just now, I realized that I had  missed a step. I needed to fill out the "When" condition. This is what had prevented the flow from being able to be active previously. After filling that out and using a tag "kitinerary", I was able to successfully set up the flow. My apologies for the confusion.

The flow is not working, however. I have saved a couple of travel related emails to PDF files. One is a parking reservation, the other is flight information. They are saved in a folder with the "kitinerary" tag. I also added the "kitinerary" tag through the Nextcloud files page. After a couple of minutes, I refreshed my calendar page, but neither thing showed up.

I see errors related to kitinerary in the logs, attached. It starts with
```
[webdav] Error: Error: Call to a member function getIterator() on null at <<closure>>
```

If appropriate, I can create a new issue for this or add to an issue if there's already one open.


[kitinerary_error_log.txt](https://github.com/MCMic/workflow_kitinerary/files/10473281/kitinerary_error_log.txt)

**Comment by MCMic** [comment]
@TraceyC77 Yes, please open an other ticket for this error please.

I will fix it but most likely it means it failed to extract information from your files.
I do not think kitinerary works for email turned to PDF. It works best on ticket files directly.

And for extracting from emails you should either use the kmail integration or the Nextcloud mail integration.
Or maybe if you save the emails directly in text format it works better, not sure. You can use kitinerary-extractor in cli on files to test what works and what not.
