### ISSUE TITLE
Switch to NcSelect and fix UI

### ISSUE THREAD

**Issue by come-nc** [MCMic/workflow_kitinerary#35]
When openining flow configuration, if there are existing kitinerary flows setup, the selected calendar for them is not selected on opening.
Also, behavior is weird when using the select.

It would be cool to switch to NcSelect once nextcloud/vue 7.4 is used, and fix those problems.

**Comment by come-nc** [comment]
ping @Pytal

**Comment by yeupou** [comment]
Same issue. 

Plus I can only have the "when... flag is TravelTicket" regepx, if I try to add "and filetype is PDF" it claims the regepx is invalid.

**Comment by MCMic** [comment]
Done in #86 
I was not able to set a default value :shrug: 
But at least the current value is correctly loaded now.

> Same issue.
> 
> Plus I can only have the "when... flag is TravelTicket" regepx, if I try to add "and filetype is PDF" it claims the regepx is invalid.

This is because by default mimetype is set to «match» and is only compatible with regex, you have to select «is» and then you can set PDF. This is not from this app it’s a problem with the workflowengine app from nextcloud/server.
